### PR TITLE
closes issue 5

### PR DESCRIPTION
**Pull request by arademaker**
do not merge the complete history of this branch into MASTER. Only the last commit is relevant. As far as I know, using `squash` you will make all the commits in the branch into a single commit without preserving the intermediary files.

### CODE REVIEW

**Comment by huaiyu-zhu** [comment]
To clarify this pull request:
- The discussion leading to the final result are in #5.  In this version it is decided to use the format with variable number of columns.  Additional suggestions in #5 are left to the future.
- The description of the final result is in the README file at https://github.com/System-T/UniversalPropositions/tree/issue-5/UP_English-EWT
- The review of this pull request is to validate the description in the README file against the actual result.

**Review by huaiyu-zhu — CHANGES_REQUESTED** [review]
To be consistent with the convention used for other languages in this project, we need to change ARG0 to A0 and ARGM-TMP to AM-TMP, etc.

**Comment by arademaker** [comment]
Hi @huaiyu-zhu , actually I believe it is the other way around. Following the same principle that @yunyaoli evokes to keep the current format (variable number of columns) similar to what Propbank uses. I believe we should also keep the same identifiers used by Propbank. We don't change the sense identifiers (e.g. "be.01"), so why do we changed the argument identifiers? 
 
Propbank uses ARG0, ARGM-TMP, and ARGM-MOD (see http://verbs.colorado.edu/propbank/framesets-english-aliases/mantle.html). So I vote on the creation of a new issue to fix the other languages. I can handle it. As close as we follow the conventions and standards, the better will be.

**Review by huaiyu-zhu — APPROVED** [review]
Agree with keeping current arg label format of `ARG*`, and opening new issue to change from `A*` in other languages.

**Pull request merged**
